"""alert

Revision ID: e26642c1b177
Revises: ab72392f4b1b
Create Date: 2025-05-17 12:33:30.267068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e26642c1b177"
down_revision: Union[str, None] = "ab72392f4b1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("triggered_at", sa.DateTime(), nullable=True))
    op.drop_constraint("alerts_stock_id_key", "alerts", type_="unique")
    op.create_index(op.f("ix_alerts_stock_id"), "alerts", ["stock_id"], unique=False)
    op.create_index(op.f("ix_alerts_user_id"), "alerts", ["user_id"], unique=False)
    op.create_unique_constraint(
        "uix_user_stock_cond_val",
        "alerts",
        ["user_id", "stock_id", "condition", "value"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_user_stock_cond_val", "alerts", type_="unique")
    op.drop_index(op.f("ix_alerts_user_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_stock_id"), table_name="alerts")
    op.create_unique_constraint("alerts_stock_id_key", "alerts", ["stock_id"])
    op.drop_column("alerts", "triggered_at")
    # ### end Alembic commands ###
