"""color

Revision ID: 5d7b0095a987
Revises: e26642c1b177
Create Date: 2025-06-09 23:01:13.201419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d7b0095a987"
down_revision: Union[str, None] = "e26642c1b177"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "portfolio_items_stock_id_key", "portfolio_items", type_="unique"
    )
    op.create_unique_constraint(None, "portfolio_items", ["user_id", "stock_id"])
    op.add_column("stocks", sa.Column("dominant_color", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stocks", "dominant_color")
    op.drop_constraint(None, "portfolio_items", type_="unique")
    op.create_unique_constraint(
        "portfolio_items_stock_id_key", "portfolio_items", ["stock_id"]
    )
    # ### end Alembic commands ###
